pipeline {
    agent any

    tools {
        jdk 'jdk21'
        maven 'maven23'
    }

    environment {
        APP_NAME = "project1"
        IMAGE_NAME = "kondavenkat035/project1:latest"
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout Code') {
            steps {
                git branch: 'master',
                url: 'https://github.com/Kondavenkat035/DevOps-Projects.git'
            }
        }

        stage('Build Project1') {
            steps {
                dir('DevOps-Project-01/Java-Login-App') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('DevOps-Project-01') {
                    sh 'docker stop project1'
                    sh 'docker rm project1'
                    sh 'docker rmi kondavenkat035/project1:latest'
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {

                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'

                    sh 'docker push $IMAGE_NAME'
                }
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker stop project1 || true
                docker rm project1 || true

                docker run -d \
                  --name project1 \
                  -p 8089:8080 \
                  $IMAGE_NAME
                '''
            }
        }
    }

    post {
        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}
